### ISSUE TITLE
64-bit version

### ISSUE THREAD

**Issue by skypanther** [mokesmokes/titanium-ios-facebook#20]
Will you please recompile for 64-bit? Apple will require this soon. Appcelerator's 3.5+ versions will require all modules to be 64-bit. My app fails to compile with 3.5.0.RC because this module doesn't include the 64-bit architectures. Thanks.

**Comment by mokesmokes** [comment]
My thinking was to do this as soon as 3.5.0.GA is released. Haven't kept up on 3.5.0 development. Safe to build with it? This won't screw up folks working with 3.4.1.GA?

**Comment by skypanther** [comment]
If a developer has selected 3.5.0 as their default SDK (with `ti sdk select`), they will get an error when attempting to build a pre-3.5.0-based app. This is because the 3.5.0 build scripts require components within the 3.5.0 SDK. 

However, simply `ti sdk select`ing 3.4.1.GA or earlier works just fine for building such projects. Having 3.5.0 installed doesn't prevent you from building <=3.4.1 apps.

**Comment by mokesmokes** [comment]
Yup, I guess the question should be whether to include two zip files in the repo - one for 3.4 and one for 3.5.
When is 3.5.0.GA due to be released, or is there another RC planned?

**Comment by mokesmokes** [comment]
Closed by 3.21.10

**Comment by skypanther** [comment]
Thanks, and sorry for not replying to your earlier questions. I'm following up now because my earlier comment about pre-3.5 apps was wrong. You can build an app set to 3.4.x in its tiapp.xml if you have 3.5.x set as your default with `ti sdk select`. It's the converse that you can't do -- you cannot build a 3.5.x app (as set in tiapp.xml) if you have 3.4.x set as your default.

I'm not sure about another RC release. We've resolved nearly all the tickets and might just go to GA.

**Comment by mokesmokes** [comment]
@skypanther sorry to bug you on a completely unrelated note to this issue..... But as you can see I also added the Like Button to yesterday's release. I tried to add a Like button to ListItems in an Alloy project..... no can do. Noticing you're in the thick of things on Alloy - can you please help with this ticket that seems to be languishing? https://jira.appcelerator.org/browse/TC-4613
Thanks!
