### ISSUE TITLE
Already logged in

### ISSUE THREAD

**Issue by darkhorse2013** [mokesmokes/titanium-ios-facebook#26]
Hi Mokesmokes,

Great module - integrated the module easily.

A few questions:

1) After you have logged in once, if I then close the simulator then reopen it, with the old facebook module it would re-invoke the log in event handler, and proceed with log in process

//event handler to listen to user when they have logged in
facebookModule.addEventListener('login', loginSuccessCallback);

which is the equivalent of:

fb.addEventListener('login', function(e) {

where the anonymous callback function is replaced with loginSuccessCallback

With your module nothing will happen.

How can I code it so that it fires the log in event handler?

2) When I go into the screen "you are authorized to use this app", with the old facebook module it will show the app icon and person next to it - now it just shows a spanner? Is that normal?

Other then that it seems great.

Thanks for your help.

**Comment by mokesmokes** [comment]
This module also invokes the login event after the `initialize()` call, after the module starts.
The Facebook screen is Facebook's - not mine.
I suggest for general questions ask on the Appcelerator Q&A and not open issues here.
Thanks.

**Comment by darkhorse2013** [comment]
Hi,
So why is the event handler not being fired?
Regards.
Date: Fri, 13 Feb 2015 05:28:22 -0800

**Comment by mokesmokes** [comment]
I have no idea why, if you don't post the entire Facebook code flow, including window creation and opening.

**Comment by darkhorse2013** [comment]
Thanks solved it.
if (facebookModule.getLoggedIn()) {


	console.log('logged in');
	facebookModule.logout();
	facebookModule.authorize();


} else {
	console.log('not logged in');
}
That always ensures the login event handler is automatically fired if they are logged in, by first logging the user out, then logging them back in.
Great Module, I had so many problems with the old titanium module, it had very bad error handling.

**Comment by mokesmokes** [comment]
No.... you're doing something wrong. In my app the login event is called every time if the user was logged in previously, without me needing to log out.

**Comment by darkhorse2013** [comment]
Can I see your login code?

**Comment by darkhorse2013** [comment]
Here is my code
index.php

  
    
    
  
  
 		 	   		  
var loginSuccessCallback = function(e) {
	//loading symbol when logging in
	$.view_indicator.visible = true;
	Ti.API.info('[Login Pressed]');


	console.log('fb token');
	console.log(facebookModule.getAccessToken());


	if (e.success) {
		//check permissions
		facebookModule.requestWithGraphPath('me/permissions', {
			access_token : facebookModule.getAccessToken()
		}, 'GET', function(e) {
			if (e.success) {
				console.log(e.result);
				//store fb JSON Object in variable
				var fbUserPermissions = e.result;
				var declinedPermissions = process_permissions_data(fbUserPermissions);


				if (declinedPermissions.length > 0) {


					//facebookModule.logout();
					// Ask re_authorize permissions
					reauthorize_permissions(declinedPermissions);


				} else {


					//chooseExperience();
					getFbMe();


				}
			} else if (e.error) {
				console.log(e.error);
				//if there is an error , log out.
				facebookModule.logout();
				facebookModule.removeEventListener('login', loginSuccessCallback);
				facebookModule.addEventListener('login', loginSuccessCallback);
				$.view_indicator.visible = false;
			} else if (e.cancelled) {
				console.log(e.cancelled);
				facebookModule.logout();
				facebookModule.removeEventListener('login', loginSuccessCallback);
				facebookModule.addEventListener('login', loginSuccessCallback);
				$.view_indicator.visible = false;
			}
		});


		facebookModule.removeEventListener('login', loginSuccessCallback);
	} else if (e.error) {
		console.log(e.error);
		//if there is an error , log out.
		fbButton.backgroundImage = 'Button_Facebook_Normal.png';
		facebookModule.logout();
		facebookModule.removeEventListener('login', loginSuccessCallback);
		facebookModule.addEventListener('login', loginSuccessCallback);
		$.view_indicator.visible = false;
	} else if (e.cancelled) {
		console.log(e.cancelled);
		fbButton.backgroundImage = 'Button_Facebook_Normal.png';
		facebookModule.removeEventListener('login', loginSuccessCallback);
		facebookModule.addEventListener('login', loginSuccessCallback);
		$.view_indicator.visible = false;
	}


};
//elseware in code
		facebookModule.addEventListener('login', loginSuccessCallback);

**Comment by mokesmokes** [comment]
Please see the [sample project](https://github.com/mokesmokes/facebook-titanium-sample)

**Comment by darkhorse2013** [comment]
Hi mokesmokes,

I have used your sample project, the code you was referring too was         //initialize event handler
        facebookModule.initialize(6000, true); 

It works as expected, but it seems to open the Facebook login in a  web view, as opposed to log the user in automatically based on if they are logged via Facebook app settings.

This command used to be fb.ForceDialogAuth();

Any idea how to achieve this with your module? Thanks

**Comment by mokesmokes** [comment]
`initialize()` will not bring up the webview, nor the Facebook app, nor the system login. Only `authorize()` will do that. `initialize` will cause the login event to fire if there is a session open. That's it..... Perhaps there is something wrong in your configuration? You should post an entire failing project on Dropbox.

I assure you the sample app works as expected. If it doesn't, there is something wrong in your configuration. Also, try using initialize(timeout, false) first, it may be easier for you to debug. I don't recommend using the system login on iOS. It's no longer Facebook's default, and they have had bugs with that in recent SDKs.

**Comment by darkhorse2013** [comment]
Oh right that makes sense, in my click eventhandler I have facebookModule.authorize(); The trouble is it brings up the log in in a web view is that supposed to happen? i.e. asking the user to sign in with their username and password, even if they are already signed in thru the fb app.

**Comment by darkhorse2013** [comment]
fbButton.addEventListener('click', function(e) {
    fbButton.backgroundImage = 'Button_Facebook_Pressed.png';
    if (facebookModule.getLoggedIn()) {
        console.log('logged in');
        //log out, if logged in
        facebookModule.logout();
    } else {
        console.log('not logged in');
        facebookModule.authorize();

```
}
```

});

**Comment by mokesmokes** [comment]
You called `initialize(timeout, true)` which will try to login with the system login, and if there is no system Facebook account, it will call the webview. Yes, totally expected. As I wrote earlier - try calling with initialize with false.

**Comment by darkhorse2013** [comment]
![screen shot 2015-02-28 at 21 55 51](https://cloud.githubusercontent.com/assets/4923961/6428298/a3481736-bf94-11e4-8c4b-e70df0a788e9.png)
(attached log in screen after authorise is called)

Hi,

I have done that:

if (Ti.Platform.osname == 'android') {
    facebookModule.initialize(4000);
} else {
    facebookModule.initialize(6000, false);
    // pass true for system login, less reliable than app login but much faster especially on iPhone 4/4S/5
}

fbButton.addEventListener('click', function(e) {
    fbButton.backgroundImage = 'Button_Facebook_Pressed.png';
    if (facebookModule.getLoggedIn()) {
        console.log('logged in');
        //log out, if logged in
        facebookModule.logout();
    } else {
        console.log('not logged in');
        facebookModule.authorize();

```
}
```

});

But it still seems to load up the web view, instead trying to log in through the system login i.e. Facebook app irrespective no what I set the boolean for initialise.

**Comment by mokesmokes** [comment]
1. Please run the sample app. It works. If something doesn't work for you with it, it is most likely a configuration issue with your app.
2. Call initialize AFTER setting your event listeners - as in the sample app.
3. initialize(timeout, bool) : If bool is false/undefined the login preference is first Facebook app, then web login. If it is false: system login, then Facebook app if the system account was not set up, then web login if the Facebook app is not installed.
   Please test on the sample app.

**Comment by darkhorse2013** [comment]
Ok got the example file running, a couple of questions:

1) When I try to log in, I get the following error:

Invalid App Id, when the app id is valid

and 

2) can't run on device, don't have provisional profile certificate

Cheers

**Comment by darkhorse2013** [comment]
Thanks got it to work, turns out that I wasn't signed into Facebook from my phone!

**Comment by darkhorse2013** [comment]
For clarification:

```
facebookModule.initialize(6000, true);
```

--- > system log in , then web view. When I set it to true that is what happens. Provided i set my credentials in the device settings.

```
facebookModule.initialize(6000, false);
```

When I set it to false, only a web view pops up (as above). Old Facebook module, it will log in using your Facebook app credentials.

**Comment by mokesmokes** [comment]
I am setting it to false in my app, and it uses the Facebook app credentials. Something is wrong on your end, for sure.

**Comment by darkhorse2013** [comment]
Ok I copied and pasted all of your code (from the app.js) plus tiapp.xml file into my project directory - it made no difference. Web view still popped up. I believe this is called single sign on, in the old module it was forceauthoDialog box which was responsible for this.

I am using titanium alloy, SDK version 5.0, and running it on an iPhone 6. Do I need to change any settings in the Facebook developers app portal?

**Comment by mokesmokes** [comment]
Appcelerator forked my module - https://github.com/ashcoding/titanium-facebook-module - please turn to them for support, thanks. This will be the official Titanium module.

**Comment by darkhorse2013** [comment]
Great, works now. (since upgrading to that module)
