### ISSUE TITLE
Issues with 64 bits support

### ISSUE THREAD

**Issue by rpavez** [mokesmokes/titanium-ios-facebook#27]
Getting Couldn't find module: Facebook for architecture: i386 when running on Iphone 4s simulator and x86_64 when running in Iphone 5s simulator. Tried to re build the module but same error..

**Comment by mokesmokes** [comment]
did you install it local to the project or globally under ~/Library/Application Support/ etc...?

**Comment by rpavez** [comment]
Local for the project, should I install it globally?

**Comment by mokesmokes** [comment]
No, it does indeed need to be local. I have no issues with this, as do dozens of other developers. Perhaps put a zip file of a failing project on Dropbox?

**Comment by rpavez** [comment]
Sure! Here's the link https://www.dropbox.com/s/b9bgucdwbkp7smx/com.facebook-iphone-3.21.10.zip?dl=0 Thanks for your help!
Also here's my working os environment
==================================
Operating System
  Name                        = Mac OS X
  Version                     = 10.10.2
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 8.0GB

Node.js
  Node.js Version             = 0.10.13
  npm Version                 = 1.3.2

Titanium CLI
  CLI Version                 = 3.4.1
  node-appc Version           = 0.2.14

Titanium SDKs
  3.5.0.GA
    Version                   = 3.5.0

**Comment by xedef** [comment]
Hey, Rodrigo. I think what Mark meant was a link to your whole project to be able to look at the structure and how you are implementing it.
Just to confirm; have you extracted the module correctly into your project folder? This is how your project root folder should look like: http://snag.gy/ObQXG.jpg

**Comment by rpavez** [comment]
That's exactly how It looks, I can't attach my actual project since its a very big project but I can create a test project and upload.

**Comment by xedef** [comment]
Yeah, maybe that would work. ;)
Just to check first to see if this helps:
1. Have you added the module to tiapp.xml?
```<module platform="iphone" version="3.21.10">com.facebook</module> ```
2. Are you using it correclty?
```facebook = require('com.facebook');```

**Comment by rpavez** [comment]
Thanks @xedef that was the issue! I was trying to use <module platform="iphone" version="3.21.10">facebook</module> instead of <module platform="iphone" version="3.21.10">com.facebook</module>

**Comment by xedef** [comment]
Ah, great! Glad to help! :)
